/* -*- mode: c; c-basic-offset: 8; indent-tabs-mode: nil; -*-
 * vim:expandtab:shiftwidth=8:tabstop=8:
 *
 * GPL HEADER START
 *
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 only,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License version 2 for more details (a copy is included
 * in the LICENSE file that accompanied this code).
 *
 * You should have received a copy of the GNU General Public License
 * version 2 along with this program; If not, see
 * http://www.sun.com/software/products/lustre/docs/GPLv2.pdf
 *
 * Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa Clara,
 * CA 95054 USA or visit www.sun.com if you need additional information or
 * have any questions.
 *
 * GPL HEADER END
 */
/*
 * Copyright  2008 Sun Microsystems, Inc. All rights reserved
 * Use is subject to license terms.
 */
/*
 * This file is part of Lustre, http://www.lustre.org/
 * Lustre is a trademark of Sun Microsystems, Inc.
 *
 * libcfs/libcfs/errno.c
 *
 */

#include <libcfs/libcfs.h>

/*
 * Conversion tables:
 */
int cfs_errno_c2p_table[CFS_MAX_ERRNO] = {
        [CFS_EPERM] = EPERM,
        [CFS_ENOENT] = ENOENT,
        [CFS_ESRCH] = ESRCH,
        [CFS_EINTR] = EINTR,
        [CFS_EIO] = EIO,
        [CFS_ENXIO] = ENXIO,
        [CFS_E2BIG] = E2BIG,
        [CFS_ENOEXEC] = ENOEXEC,
        [CFS_EBADF] = EBADF,
        [CFS_ECHILD] = ECHILD,
        [CFS_EAGAIN] = EAGAIN,
        [CFS_ENOMEM] = ENOMEM,
        [CFS_EACCES] = EACCES,
        [CFS_EFAULT] = EFAULT,
        [CFS_ENOTBLK] = ENOTBLK,
        [CFS_EBUSY] = EBUSY,
        [CFS_EEXIST] = EEXIST,
        [CFS_EXDEV] = EXDEV,
        [CFS_ENODEV] = ENODEV,
        [CFS_ENOTDIR] = ENOTDIR,
        [CFS_EISDIR] = EISDIR,
        [CFS_EINVAL] = EINVAL,
        [CFS_ENFILE] = ENFILE,
        [CFS_EMFILE] = EMFILE,
        [CFS_ENOTTY] = ENOTTY,
        [CFS_ETXTBSY] = ETXTBSY,
        [CFS_EFBIG] = EFBIG,
        [CFS_ENOSPC] = ENOSPC,
        [CFS_ESPIPE] = ESPIPE,
        [CFS_EROFS] = EROFS,
        [CFS_EMLINK] = EMLINK,
        [CFS_EPIPE] = EPIPE,
        [CFS_EDOM] = EDOM,
        [CFS_ERANGE] = ERANGE,
        [CFS_EDEADLK] = EDEADLK,
        [CFS_ENAMETOOLONG] = ENAMETOOLONG,
        [CFS_ENOLCK] = ENOLCK,
        [CFS_ENOSYS] = ENOSYS,
        [CFS_ENOTEMPTY] = ENOTEMPTY,
        [CFS_ELOOP] = ELOOP,
        [CFS_EWOULDBLOCK] = EWOULDBLOCK,
        [CFS_ENOMSG] = ENOMSG,
        [CFS_EIDRM] = EIDRM,
        [CFS_ECHRNG] = ECHRNG,
        [CFS_EL2NSYNC] = EL2NSYNC,
        [CFS_EL3HLT] = EL3HLT,
        [CFS_EL3RST] = EL3RST,
        [CFS_ELNRNG] = ELNRNG,
        [CFS_EUNATCH] = EUNATCH,
        [CFS_ENOCSI] = ENOCSI,
        [CFS_EL2HLT] = EL2HLT,
        [CFS_EBADE] = EBADE,
        [CFS_EBADR] = EBADR,
        [CFS_EXFULL] = EXFULL,
        [CFS_ENOANO] = ENOANO,
        [CFS_EBADRQC] = EBADRQC,
        [CFS_EBADSLT] = EBADSLT,
        [CFS_EDEADLOCK] = EDEADLOCK,
        [CFS_EBFONT] = EBFONT,
        [CFS_ENOSTR] = ENOSTR,
        [CFS_ENODATA] = ENODATA,
        [CFS_ETIME] = ETIME,
        [CFS_ENOSR] = ENOSR,
        [CFS_ENONET] = ENONET,
        [CFS_ENOPKG] = ENOPKG,
        [CFS_EREMOTE] = EREMOTE,
        [CFS_ENOLINK] = ENOLINK,
        [CFS_EADV] = EADV,
        [CFS_ESRMNT] = ESRMNT,
        [CFS_ECOMM] = ECOMM,
        [CFS_EPROTO] = EPROTO,
        [CFS_EMULTIHOP] = EMULTIHOP,
        [CFS_EBADMSG] = EBADMSG,
        [CFS_EOVERFLOW] = EOVERFLOW,
        [CFS_ENOTUNIQ] = ENOTUNIQ,
        [CFS_EBADFD] = EBADFD,
        [CFS_EREMCHG] = EREMCHG,
        [CFS_ELIBACC] = ELIBACC,
        [CFS_ELIBBAD] = ELIBBAD,
        [CFS_ELIBSCN] = ELIBSCN,
        [CFS_ELIBMAX] = ELIBMAX,
        [CFS_ELIBEXEC] = ELIBEXEC,
        [CFS_EILSEQ] = EILSEQ,
        [CFS_ERESTART] = ERESTART,
        [CFS_ESTRPIPE] = ESTRPIPE,
        [CFS_EUSERS] = EUSERS,
        [CFS_ENOTSOCK] = ENOTSOCK,
        [CFS_EDESTADDRREQ] = EDESTADDRREQ,
        [CFS_EMSGSIZE] = EMSGSIZE,
        [CFS_EPROTOTYPE] = EPROTOTYPE,
        [CFS_ENOPROTOOPT] = ENOPROTOOPT,
        [CFS_EPROTONOSUPPORT] = EPROTONOSUPPORT,
        [CFS_ESOCKTNOSUPPORT] = ESOCKTNOSUPPORT,
        [CFS_EOPNOTSUPP] = EOPNOTSUPP,
        [CFS_EPFNOSUPPORT] = EPFNOSUPPORT,
        [CFS_EAFNOSUPPORT] = EAFNOSUPPORT,
        [CFS_EADDRINUSE] = EADDRINUSE,
        [CFS_EADDRNOTAVAIL] = EADDRNOTAVAIL,
        [CFS_ENETDOWN] = ENETDOWN,
        [CFS_ENETUNREACH] = ENETUNREACH,
        [CFS_ENETRESET] = ENETRESET,
        [CFS_ECONNABORTED] = ECONNABORTED,
        [CFS_ECONNRESET] = ECONNRESET,
        [CFS_ENOBUFS] = ENOBUFS,
        [CFS_EISCONN] = EISCONN,
        [CFS_ENOTCONN] = ENOTCONN,
        [CFS_ESHUTDOWN] = ESHUTDOWN,
        [CFS_ETOOMANYREFS] = ETOOMANYREFS,
        [CFS_ETIMEDOUT] = ETIMEDOUT,
        [CFS_ECONNREFUSED] = ECONNREFUSED,
        [CFS_EHOSTDOWN] = EHOSTDOWN,
        [CFS_EHOSTUNREACH] = EHOSTUNREACH,
        [CFS_EALREADY] = EALREADY,
        [CFS_EINPROGRESS] = EINPROGRESS,
        [CFS_ESTALE] = ESTALE,
        [CFS_ENAVAIL] = ENAVAIL,
        [CFS_EDQUOT] = EDQUOT,
        [CFS_ENOMEDIUM] = ENOMEDIUM,
        [CFS_ECANCELED] = ECANCELED,
        [CFS_EOWNERDEAD] = EOWNERDEAD,
        [CFS_ENOTRECOVERABLE] = ENOTRECOVERABLE,
        [CFS_ERESTARTSYS] = ERESTARTSYS,
        [CFS_ENOTSUPP] = ENOTSUPP,
};

int cfs_errno_p2c_table[CFS_MAX_ERRNO] = {
        [EPERM] = CFS_EPERM,
        [ENOENT] = CFS_ENOENT,
        [ESRCH] = CFS_ESRCH,
        [EINTR] = CFS_EINTR,
        [EIO] = CFS_EIO,
        [ENXIO] = CFS_ENXIO,
        [E2BIG] = CFS_E2BIG,
        [ENOEXEC] = CFS_ENOEXEC,
        [EBADF] = CFS_EBADF,
        [ECHILD] = CFS_ECHILD,
        [EAGAIN] = CFS_EAGAIN,
        [ENOMEM] = CFS_ENOMEM,
        [EACCES] = CFS_EACCES,
        [EFAULT] = CFS_EFAULT,
        [ENOTBLK] = CFS_ENOTBLK,
        [EBUSY] = CFS_EBUSY,
        [EEXIST] = CFS_EEXIST,
        [EXDEV] = CFS_EXDEV,
        [ENODEV] = CFS_ENODEV,
        [ENOTDIR] = CFS_ENOTDIR,
        [EISDIR] = CFS_EISDIR,
        [EINVAL] = CFS_EINVAL,
        [ENFILE] = CFS_ENFILE,
        [EMFILE] = CFS_EMFILE,
        [ENOTTY] = CFS_ENOTTY,
        [ETXTBSY] = CFS_ETXTBSY,
        [EFBIG] = CFS_EFBIG,
        [ENOSPC] = CFS_ENOSPC,
        [ESPIPE] = CFS_ESPIPE,
        [EROFS] = CFS_EROFS,
        [EMLINK] = CFS_EMLINK,
        [EPIPE] = CFS_EPIPE,
        [EDOM] = CFS_EDOM,
        [ERANGE] = CFS_ERANGE,
        [EDEADLK] = CFS_EDEADLK,
        [ENAMETOOLONG] = CFS_ENAMETOOLONG,
        [ENOLCK] = CFS_ENOLCK,
        [ENOSYS] = CFS_ENOSYS,
        [ENOTEMPTY] = CFS_ENOTEMPTY,
        [ELOOP] = CFS_ELOOP,
        [EWOULDBLOCK] = CFS_EWOULDBLOCK,
        [ENOMSG] = CFS_ENOMSG,
        [EIDRM] = CFS_EIDRM,
        [ECHRNG] = CFS_ECHRNG,
        [EL2NSYNC] = CFS_EL2NSYNC,
        [EL3HLT] = CFS_EL3HLT,
        [EL3RST] = CFS_EL3RST,
        [ELNRNG] = CFS_ELNRNG,
        [EUNATCH] = CFS_EUNATCH,
        [ENOCSI] = CFS_ENOCSI,
        [EL2HLT] = CFS_EL2HLT,
        [EBADE] = CFS_EBADE,
        [EBADR] = CFS_EBADR,
        [EXFULL] = CFS_EXFULL,
        [ENOANO] = CFS_ENOANO,
        [EBADRQC] = CFS_EBADRQC,
        [EBADSLT] = CFS_EBADSLT,
        [EDEADLOCK] = CFS_EDEADLOCK,
        [EBFONT] = CFS_EBFONT,
        [ENOSTR] = CFS_ENOSTR,
        [ENODATA] = CFS_ENODATA,
        [ETIME] = CFS_ETIME,
        [ENOSR] = CFS_ENOSR,
        [ENONET] = CFS_ENONET,
        [ENOPKG] = CFS_ENOPKG,
        [EREMOTE] = CFS_EREMOTE,
        [ENOLINK] = CFS_ENOLINK,
        [EADV] = CFS_EADV,
        [ESRMNT] = CFS_ESRMNT,
        [ECOMM] = CFS_ECOMM,
        [EPROTO] = CFS_EPROTO,
        [EMULTIHOP] = CFS_EMULTIHOP,
        [EBADMSG] = CFS_EBADMSG,
        [EOVERFLOW] = CFS_EOVERFLOW,
        [ENOTUNIQ] = CFS_ENOTUNIQ,
        [EBADFD] = CFS_EBADFD,
        [EREMCHG] = CFS_EREMCHG,
        [ELIBACC] = CFS_ELIBACC,
        [ELIBBAD] = CFS_ELIBBAD,
        [ELIBSCN] = CFS_ELIBSCN,
        [ELIBMAX] = CFS_ELIBMAX,
        [ELIBEXEC] = CFS_ELIBEXEC,
        [EILSEQ] = CFS_EILSEQ,
        [ERESTART] = CFS_ERESTART,
        [ESTRPIPE] = CFS_ESTRPIPE,
        [EUSERS] = CFS_EUSERS,
        [ENOTSOCK] = CFS_ENOTSOCK,
        [EDESTADDRREQ] = CFS_EDESTADDRREQ,
        [EMSGSIZE] = CFS_EMSGSIZE,
        [EPROTOTYPE] = CFS_EPROTOTYPE,
        [ENOPROTOOPT] = CFS_ENOPROTOOPT,
        [EPROTONOSUPPORT] = CFS_EPROTONOSUPPORT,
        [ESOCKTNOSUPPORT] = CFS_ESOCKTNOSUPPORT,
        [EOPNOTSUPP] = CFS_EOPNOTSUPP,
        [EPFNOSUPPORT] = CFS_EPFNOSUPPORT,
        [EAFNOSUPPORT] = CFS_EAFNOSUPPORT,
        [EADDRINUSE] = CFS_EADDRINUSE,
        [EADDRNOTAVAIL] = CFS_EADDRNOTAVAIL,
        [ENETDOWN] = CFS_ENETDOWN,
        [ENETUNREACH] = CFS_ENETUNREACH,
        [ENETRESET] = CFS_ENETRESET,
        [ECONNABORTED] = CFS_ECONNABORTED,
        [ECONNRESET] = CFS_ECONNRESET,
        [ENOBUFS] = CFS_ENOBUFS,
        [EISCONN] = CFS_EISCONN,
        [ENOTCONN] = CFS_ENOTCONN,
        [ESHUTDOWN] = CFS_ESHUTDOWN,
        [ETOOMANYREFS] = CFS_ETOOMANYREFS,
        [ETIMEDOUT] = CFS_ETIMEDOUT,
        [ECONNREFUSED] = CFS_ECONNREFUSED,
        [EHOSTDOWN] = CFS_EHOSTDOWN,
        [EHOSTUNREACH] = CFS_EHOSTUNREACH,
        [EALREADY] = CFS_EALREADY,
        [EINPROGRESS] = CFS_EINPROGRESS,
        [ESTALE] = CFS_ESTALE,
        [ENAVAIL] = CFS_ENAVAIL,
        [EDQUOT] = CFS_EDQUOT,
        [ENOMEDIUM] = CFS_ENOMEDIUM,
        [ECANCELED] = CFS_ECANCELED,
        [EOWNERDEAD] = CFS_EOWNERDEAD,
        [ENOTRECOVERABLE] = CFS_ENOTRECOVERABLE,
        [ERESTARTSYS] = CFS_ERESTARTSYS,
        [ENOTSUPP] = CFS_ENOTSUPP,
};
